[env:d1_mini_pro]
platform = espressif8266
board = d1_mini_pro
framework = arduino
monitor_speed = 115200
monitor_port = /dev/ttyUSB0       ; Linux/Mac
; monitor_port = COM3             ; Windows

; monitor_filters = esp8266_exception_decoder

build_flags =
    -D PIO_FRAMEWORK_ARDUINO
    -D ARDUINO_ARCH_ESP8266

; board_build.flash_size = 16MB
; board_build.ldscript = eagle.flash.16m.ld
