[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

monitor_speed = 115200
upload_speed = 921600
upload_resetmethod = nodemcu

build_type = release
board_build.filesystem = littlefs

lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4

build_flags =
    -std=c++17
    -Os
    -Wall
    -Wextra
    -fno-exceptions
    -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
