[env:receptor_bocina]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_flags =
    -I../
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.5

[env:receptor_bocina_ota]
extends = env:receptor_bocina
upload_protocol = espota
upload_port = 192.168.0.201
