[env:receptor_central_unificado]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_flags =
    -I../
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.5
lib_extra_dirs =
    ../lib

[env:receptor_central_unificado_ota]
extends = env:receptor_central_unificado
upload_protocol = espota
upload_port = 192.168.0.201
